[colors.primary]
background = "#fff7ed"
foreground = "#1e293b"
dim_foreground = "#64748b"
bright_foreground = "#0f172a"

[colors.cursor]
text = "#fff7ed"
cursor = "#0ea5e9"

[colors.vi_mode_cursor]
text = "#fff7ed"
cursor = "#fb923c"

[colors.search.matches]
foreground = "#fff7ed"
background = "#64748b"

[colors.search.focused_match]
foreground = "#fff7ed"
background = "#0ea5e9"

[colors.footer_bar]
foreground = "#fff7ed"
background = "#64748b"

[colors.hints.start]
foreground = "#fff7ed"
background = "#fbbf24"

[colors.hints.end]
foreground = "#fff7ed"
background = "#64748b"

[colors.selection]
text = "#fff7ed"
background = "#0369a1"

[colors.normal]
black = "#1e293b"
red = "#fb923c"
green = "#0ea5e9"
yellow = "#fbbf24"
blue = "#0ea5e9"
magenta = "#fb923c"
cyan = "#0ea5e9"
white = "#ffffff"

[colors.bright]
black = "#475569"
red = "#f97316"
green = "#38bdf8"
yellow = "#facc15"
blue = "#38bdf8"
magenta = "#f97316"
cyan = "#38bdf8"
white = "#ffffff"

[font]
size = 12.0

[window]
opacity = 0.95
padding = { x = 10, y = 10 }